In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import brown
import enchant
import datetime
d = enchant.Dict("en_US")
word_set = set(brown.words())

In [184]:
# SET UP DATA

# convert csv to a pandas DataFrame format
train_df = pd.DataFrame.from_csv('data/train.csv')
test_df = pd.DataFrame.from_csv('data/test.csv')

In [7]:
# BASIC DATASET INFORMATION

# -- our train set is 1089 x 17
print(train_df.shape)
# -- our test set is 300 x 15 (the 2 missing columns are the label and a redundant field that resembles label)
print(test_df.shape)

(1089, 17)
(300, 15)


In [8]:
train_df.shape[0]

1089

In [9]:
# FIGURE OUT LABEL DISTRIBUTION [~57% of dataset came from Android]

# create dataset with only positive labels -- 619 positive labels in training set
df_train_pos = train_df[train_df.label == 1]
# create dataset with only negative labels -- 470 negative labels in training set
df_train_neg = train_df[train_df.label == -1]
print("Number of positive [Android] training points: " + str(len(df_train_pos)))
print("Number of negative [iPhone] training points: " + str(len(df_train_neg)))
print("Percentage of training points from Android: " + str(len(df_train_pos)/train_df.shape[0]))

Number of positive [Android] training points: 619
Number of negative [iPhone] training points: 470
Percentage of training points from Android: 0


In [130]:
predictions2 = rf2.predict(validate_features)
predictions3 = rf3.predict(validate_features)
predictions4 = rf4.predict(validate_features)
predictions5 = rf5.predict(validate_features)

In [132]:
pred_sum = predictions+predictions2+predictions3+predictions4+predictions5

In [135]:
clipped_sum = np.clip(pred_sum, -1, 1)

In [138]:
sum(clipped_sum == validate_labels)

194

In [74]:
# Use the forest's predict method on the test data
predictions = rf.predict(validate_features)
# Calculate the absolute errors
errors = abs(predictions - validate_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

('Mean Absolute Error:', 0.22, 'degrees.')


In [106]:
feature_list

['favoriteCount',
 'retweetCount',
 'in_quotes',
 'uses_own_handle',
 'contains_http',
 'contains_hashtag',
 'num_of_misspellings',
 'contains_emojis',
 'length',
 'time_of_day_sec']

In [107]:
test_df.columns

Index([u'favoriteCount', u'retweetCount', u'in_quotes', u'uses_own_handle',
       u'contains_http', u'contains_hashtag', u'contains_emojis', u'length',
       u'num_of_misspellings'],
      dtype='object')

In [113]:
# Use the forest's predict method on the test data
real_predictions = rf.predict(test_df)

In [198]:
ensemble_df = pd.DataFrame(np.arange(300))

In [199]:
ensemble_df['Label'] = ensemble_pred

In [200]:
ensemble_df.rename(index=str, columns={"0": "ID", "Label": "Label"})

0  Label
0      0      1
1      1      1
2      2     -1
3      3      1
4      4      1
5      5      1
6      6     -1
7      7     -1
8      8      1
9      9     -1
10    10      1
11    11      1
12    12      1
13    13      1
14    14     -1
15    15     -1
16    16     -1
17    17     -1
18    18     -1
19    19      1
20    20      1
21    21     -1
22    22      1
23    23      1
24    24     -1
25    25     -1
26    26     -1
27    27     -1
28    28     -1
29    29     -1
..   ...    ...
270  270     -1
271  271      1
272  272      1
273  273      1
274  274      1
275  275      1
276  276      1
277  277     -1
278  278     -1
279  279      1
280  280      1
281  281      1
282  282     -1
283  283     -1
284  284     -1
285  285      1
286  286     -1
287  287     -1
288  288      1
289  289     -1
290  290      1
291  291      1
292  292      1
293  293     -1
294  294      1
295  295      1
296  296      1
297  297      1
298  298      1
299  299     -1

[300 rows x 2 columns]

In [201]:
ensemble_df.to_csv('predictions_2ada1rf.csv', index=False)

In [121]:
real_pred = pd.DataFrame(np.arange(300))

In [123]:
real_pred['Label'] = real_predictions

In [128]:
real_pred.to_csv('predictions_rf.csv', index=False)

In [116]:
 real_pred.rename(index=str, columns={"0": "a", "B": "c"})

0
0    1
1   -1
2   -1
3    1
4    1
5    1
6   -1
7   -1
8    1
9   -1
10   1
11   1
12   1
13   1
14  -1
15  -1
16  -1
17  -1
18  -1
19  -1
20   1
21  -1
22   1
23   1
24  -1
25  -1
26  -1
27  -1
28  -1
29  -1
..  ..
270 -1
271  1
272  1
273  1
274  1
275  1
276  1
277 -1
278 -1
279  1
280  1
281  1
282 -1
283 -1
284 -1
285  1
286 -1
287 -1
288  1
289 -1
290  1
291  1
292  1
293 -1
294  1
295  1
296 -1
297  1
298  1
299 -1

[300 rows x 1 columns]

In [185]:
# CREATING FEATURES

# DROPPING IRRELEVANT COLUMNS
test_df = test_df.drop(['favorited', 'truncated', 'replyToSID', 'id.1', 'replyToUID', 'screenName', 'isRetweet', 'retweeted','longitude', 'latitude'], axis=1)


#if tweet starts with quote
quotes = [t[0] == '"' for t in test_df['text']]
test_df['in_quotes'] = quotes

#it tweet contains @realdonaldtrump
test_df['uses_own_handle'] = ["@realDonaldTrump" in t for t in test_df['text']]

#if tweet contains http
test_df['contains_http'] = ["http" in t for t in test_df['text']]

#if tweet contains hashtag
test_df['contains_hashtag'] = ["#" in t for t in test_df['text']]

#check misspellings
word_set = set(brown.words())
def spell_check_sentence(sentence):
    misspelled = [not d.check(x) if x!= "" else False for x in sentence.split(" ")]
    return sum(misspelled)

#check for emojis (U+)
test_df['contains_emojis'] = ["U+" in t for t in test_df['text']]

#check length
test_df['length'] = [len(t) for t in test_df['text']]

#check num of mispellings
test_df['num_of_misspellings'] = [spell_check_sentence(s) for s in test_df['text']]



array([ 1,  1, -1,  1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1, -1, -1,
       -1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,
        1,  1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1,  1,
       -1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1, -1,  1,  1, -1,
        1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1, -1,
       -1,  1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1,
        1,  1, -1,  1,  1

In [186]:
times = [t.split(' ')[1].split(':') for t in test_df['created']]
test_df['time_of_day_sec'] = [datetime.timedelta(hours = int(time[0]), minutes = int(time[1])).seconds for time in times]

In [189]:
test_df['contains_any_at'] = ['@' in s for s in test_df['text']]
test_df = test_df.drop(['text', 'replyToSN', 'created'], axis = 1)

In [190]:
test_df

favoriteCount  retweetCount  in_quotes  uses_own_handle  contains_http  \
id                                                                            
0             9214          3107      False            False          False   
1             6981          2390      False            False           True   
2            15724          6691      False            False           True   
3            19837          6402      False            False          False   
4            34051         11717      False            False          False   
5            29831          9892      False            False          False   
6            19223          5784      False            False           True   
7            19543          7930      False            False           True   
8            75488         24663      False            False          False   
9            23661          7903      False            False           True   
10           28069          8561      False            False          False   
11           35205         13129      False            False          False   
12           36936         13250      False            False          False   
13           32716          9356      False            False          False   
14           34109         10385      False            False           True   
15           19436          8066      False            False           True   
16           19330          5418      False            False           True   
17           19431          5681      False            False           True   
18           27568         13869      False            False           True   
19           25860          8989      False            False           True   
20           26919          8674      False            False          False   
21           32750         12351      False            False           True   
22           36899         13107      False            False          False   
23           34549         11863      False            False          False   
24           13737          4202      False            False           True   
25           18101          5337      False            False           True   
26           34671         10602      False            False           True   
27           19434          5804      False            False           True   
28           18501          5722      False            False           True   
29           23610          7402      False            False           True   
..             ...           ...        ...              ...            ...   
270          23595          7518      False            False           True   
271          45230         16163      False            False          False   
272          26528          8149      False            False          False   
273          18114          5449      False            False          False   
274          21209          5711      False            False          False   
275          17033          4099      False            False          False   
276          24799          8090      False            False          False   
277          16007          5012      False            False          False   
278          18698          7799      False            False           True   
279          15001          4438      False            False          False   
280          15131          4488      False            False          False   
281          18246          6019      False            False          False   
282          21763          8053      False            False           True   
283          29865         11571      False            False           True   
284          19173          6460      False            False           True   
285          35235         11478      False            False          False   
286          19472          5659      False            False           True   
287          16638          5659      False            

In [180]:
real_predictions = rf.predict(test)

NameError: name 'test' is not defined

In [82]:
sum(validate_labels == predictions)

194

In [83]:
len(validate_labels)

218

In [84]:
194/218.

0.8899082568807339

In [85]:
validate_labels == predictions

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [79]:
validate_labels

array([ 1, -1,  1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1,
        1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,  1,
        1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1, -1,  1, -1,
       -1,  1, -1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1,  1,  1,
       -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,  1, -1,
        1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1,
       -1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1,
       -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,
        1, -1,  1, -1,  1, -1,  1, -1,  1, -1, -1,  1,  1,  1, -1,  1,  1,
       -1, -1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1])

In [77]:
predictions

array([ 1, -1,  1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1, -1,  1, -1,  1,
        1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1, -1,  1,  1,
        1, -1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1,  1,  1, -1,  1, -1,
       -1,  1, -1, -1, -1,  1,  1, -1, -1,  1,  1, -1,  1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1,  1,
       -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,  1, -1,
        1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,  1,  1,
       -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1, -1,
       -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,
        1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1])

In [87]:
errors

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0])

In [76]:
mape = 100 * (errors / validate_labels)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

('Accuracy:', 111.01, '%.')


In [94]:
test_df = create_features(test_df)

ValueError: labels ['statusSource'] not contained in axis

In [ ]:

# Labels are the values we want to predict
labels = np.array(features['actual'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('actual', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)